<?php

namespace Mahmoud\EventBundle\Repository;

/**
 * EventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRepository extends \Doctrine\ORM\EntityRepository
{
    public function findEventByUser($id)
    {
        $query =$this->createQueryBuilder('e')
            ->innerJoin('e.userId','u')
            ->where('u.id =:id ')
            ->setParameters(array(
                'id'=>$id
            ))
            ->getQuery();
        return $query->getResult();
    }

    public function topFive()
    {
        $query =$this->createQueryBuilder('e')
            ->setMaxResults(5)
            ->orderBy('e.id', 'DESC')
            ->getQuery();
        return $query->getResult();
    }
    public function findEventById($id)
    {
        $query =$this->createQueryBuilder('e')
            ->where('e.id =:id ')
            ->setParameters(array(
                'id'=>$id
            ))
            ->getQuery();
        return $query->getResult();
    }

    public function findPhoto(){
        return $this->getEntityManager()
            ->createQuery(
                'SELECT e.eventPicture
                FROM MahmoudEventBundle:Event e
                WHERE e.id = 1
                ')
            ->getResult();
    }


    public function findEntitiesByString($str){
        return $this->getEntityManager()
            ->createQuery(
                'SELECT e
                FROM MahmoudEventBundle:Event e
                WHERE e.eventDescription LIKE :str OR e.eventCountry LIKE :str OR e.eventCountry LIKE :str OR e.eventCategory LIKE :str OR e.eventTitle LIKE :str  '
            )
            ->setParameter('str', '%'.$str.'%')
            ->getResult();
    }

    public function findEntitiesByDescription($str){
        return $this->getEntityManager()
            ->createQuery(
                'SELECT e
                FROM MahmoudEventBundle:Event e
                WHERE e.eventDescription LIKE :str'
            )
            ->setParameter('str', '%'.$str.'%')
            ->getResult();
    }
    public function findEntitiesByCountry($str){
        return $this->getEntityManager()
            ->createQuery(
                'SELECT e
                FROM MahmoudEventBundle:Event e
                WHERE e.eventCountry LIKE :str'
            )
            ->setParameter('str', '%'.$str.'%')
            ->getResult();
    }

    public function findEntitiesByCategory($str){
        return $this->getEntityManager()
            ->createQuery(
                'SELECT e
                FROM MahmoudEventBundle:Event e
                WHERE e.eventCategory LIKE :str'
            )
            ->setParameter('str', '%'.$str.'%')
            ->getResult();
    }

}
