<?php

namespace Mahmoud\EventBundle\Repository;

/**
 * EventLocationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventLocationRepository extends \Doctrine\ORM\EntityRepository
{

public function findByEventId($id)
{
    $query =$this->createQueryBuilder('l')
        ->innerJoin('l.eventId','e')
        ->where('e.id =:id ')
        ->setParameters(array(
            'id'=>$id
        ))
        ->getQuery();
    return $query->getOneOrNullResult();
}

    public function findLocationByEventId($id)
    {
        $query =$this->createQueryBuilder('l')
            ->innerJoin('l.eventId','e')
            ->where('l.eventId =:id ')
            ->setParameters(array(
                'id'=>$id
            ))
            ->getQuery();
        return $query->getResult();
    }

}
