<?php

namespace Mahmoud\EventBundle\Repository;

/**
 * ReservationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReservationRepository extends \Doctrine\ORM\EntityRepository
{


    public function isFound($ide,$idu)
    {
        $query =$this->createQueryBuilder('r')

            ->where('r.eventId =:ide ')
            ->andWhere('r.userId =:idu ')
            ->setParameters(array(
                'ide'=>$ide,
                'idu'=>$idu
            ))
            ->getQuery();
        return $query->getOneOrNullResult();
    }

    public function findReservationByUser($id)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT r
                FROM MahmoudEventBundle:Reservation r
                WHERE r.userId =:id'
            )
            ->setParameter("id",$id)
            ->getResult();
    }




    public function findByuserId($idu)
    {
        $query =$this->createQueryBuilder('r')
            ->Where('r.userId =:idu ')
            ->setParameters(array(
                'idu'=>$idu
            ))
            ->getQuery();
        return $query->getResult();
    }

    public function countAllReservation()
    { return $this->getEntityManager()
        ->createQuery(
            'SELECT count(e.id)
                FROM MahmoudEventBundle:Reservation e
              ')
        ->getSingleScalarResult();

    }

    public function countReservationByEvent($id)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT count(e.id)
                FROM MahmoudEventBundle:Reservation e
                 WHERE e.eventId = :str
              '
            )
            ->setParameter('str', $id)
            ->getSingleScalarResult();
    }



}
