<?php

namespace ForumBundle\Repository;

/**
 * CategorieSuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategorieSuRepository extends \Doctrine\ORM\EntityRepository
{
}
