<?php

namespace ForumBundle\Repository;

/**
 * CommentaireSuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentaireSuRepository extends \Doctrine\ORM\EntityRepository
{
    public function findname()
    {
        $q = $this->getEntityManager()->createQuery("SELECT p from ForumBundle:CommentaireSu p JOIN p.user b  ");
        return $query = $q->getResult();
    }
}
