<?php

namespace ForumBundle\Repository;

/**
 * SujetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SujetRepository extends \Doctrine\ORM\EntityRepository

{
    public function findSujetByUser($id)
    {
        $query = $this->createQueryBuilder('e')
            ->innerJoin('e.user', 'u')
            ->where('u.id =:id ')
            ->setParameters(array(
                'id' => $id
            ))
            ->getQuery();
        return $query->getResult();
    }

    public function findname()
    {
        $q = $this->getEntityManager()->createQuery("SELECT p from ForumBundle:Sujet p JOIN p.user b  ");
        return $query = $q->getResult();
    }


}
